GoogleContainerTools/kpt-backstage-plugins

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
This change adds bug and feature request issue templates and adds issue contact links.
> chore: configure issue templates

- packages/app/package.json
This change updates the example application to use the latest Configuration as Data plugin.
> fix: update example application to use latest plugin

- plugins/cad/src/components/PackageRevisionPage/PackageRevisionPage.tsx
- plugins/cad/src/components/PackageRevisionPage/components/PackageRevisionsTable.tsx
This change adds new columns to the Package Revisions Table which shows the total number of resources and the number of resources added, updated, and removed in each revision.
> feat: show changes summary on package revisions table

- plugins/cad/src/components/ResourceEditorDialog/components/FirstClassEditors/RoleBindingEditor/RoleBindingEditor.tsx
- plugins/cad/src/components/ResourceEditorDialog/components/FirstClassEditors/RoleBindingEditor/components/SubjectEditorAccordion.tsx
This change adds service account autocompletion to the Role Binding Editor.
> feat: add service account autocompletion to role binding editor

- plugins/cad/src/components/Controls/IconButton.tsx
- plugins/cad/src/components/Controls/index.ts
- plugins/cad/src/components/PackageRevisionPage/components/PackageRevisionResourcesTable.tsx
- plugins/cad/src/components/PackageRevisionPage/components/PackageRevisionsTable.tsx
- plugins/cad/src/components/RepositoryPage/components/PackageSummaryTable.tsx
- plugins/cad/src/components/ResourceEditorDialog/components/FirstClassEditors/Controls/KeyValueEditorAccordion.tsx
This change adds hover and focus text to all icon buttons.
> feat: add tooltips to all icon buttons

- plugins/cad/src/types/PackageRevision.ts
- plugins/cad/src/utils/packageRevision.ts
This change updates the the package upgrade logic to use the merge update strategy.
> feat: use merge update strategy for package upgrades

- plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewerSelector.tsx
This change adds Cluster Role and Cluster Role Binding resource viewers.
> feat: add cluster role and cluster role binding resource viewers

- plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewerSelector.tsx
- plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewers/StructuredMetadata/resources/persistentVolumeClaim.ts
- plugins/cad/src/types/PersistentVolumeClaim.ts
This change adds a Persistent Volume Claim resource viewer.
> feat: add persistent volume claim resource viewer

- plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewerSelector.tsx
- plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewers/StructuredMetadata/resources/service.ts
- plugins/cad/src/types/Service.ts
This change adds a Service resource viewer.
> feat: add service resource viewer

- plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewerSelector.tsx
- plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewers/StructuredMetadata/resources/setLabels.ts
- plugins/cad/src/types/SetLabels.ts
This change adds the Set Labels resource viewer.
> feat: add set labels resource viewer

- plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewerSelector.tsx
- plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewers/StructuredMetadata/resources/starlarkRun.ts
- plugins/cad/src/types/StarlarkRun.ts
This change adds the Starlark Run resource viewer.
> feat: add starlark run resource viewer

- plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewerSelector.tsx
- plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewers/StructuredMetadata/resources/ingress.ts
- plugins/cad/src/types/Ingress.ts
This change adds the Ingress resource viewer.
> feat: add ingress resource viewer

- plugins/cad/src/components/PackageRevisionPage/components/PackageRevisionResourcesTable.tsx
- plugins/cad/src/components/ResourceEditorDialog/components/FirstClassEditorSelector.tsx
- plugins/cad/src/components/ResourceEditorDialog/components/FirstClassEditors/SetLabelsEditor/SetLabelsEditor.tsx
- plugins/cad/src/components/ResourceEditorDialog/components/FirstClassEditors/SetLabelsEditor/index.ts
This change adds the Set Labels resource editor.
> feat: add set labels resource editor

- plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewerSelector.tsx
- plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewers/StructuredMetadata/resources/clusterIssuer.ts
- plugins/cad/src/types/ClusterIssuer.ts
This change adds the Cluster Issuer resource viewer.
> feat: add cluster issuer resource viewer

- plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewers/StructuredMetadata/resources/persistentVolumeClaim.ts
This change updates the Persistent Volume Claim resource viewer.
> feat: update persistent volume claim resource viewer

- plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewerSelector.tsx
- plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewers/StructuredMetadata/resources/deployment.ts
- plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewers/StructuredMetadata/resources/podTemplate.ts
- plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewers/StructuredMetadata/resources/statefulSet.ts
- plugins/cad/src/types/Deployment.ts
- plugins/cad/src/types/Pod.ts
- plugins/cad/src/types/StatefulSet.ts
This change adds the Deployment and Stateful Set resource viewers.
> feat: add deployment and stateful set resource viewers

- .gitignore
- plugins/cad/src/components/RepositoryPage/RepositoryPage.tsx
- plugins/cad/src/components/RepositoryPage/components/AdvancedRepositoryOptions.tsx
Signed-off-by: Tathagata Paul <tathagatapaul7@gmail.com>
This PR will automatically delete repository secret on unregistering the repository.
> feat: delete repository secret on unregistering repository

- plugins/cad/src/components/PackageRevisionPage/updatedResourcesMap/processUpdatedResourcesMap.ts
- plugins/cad/src/components/PackageRevisionPage/updatedResourcesMap/resources/setLabels.ts
This change adds the set labels function automatically to the Kptfile when a new Set Labels resource is added to a package.
> feat: add set labels function automatically

- plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewerSelector.tsx
- plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewers/StructuredMetadata/resources/ingressClass.ts
- plugins/cad/src/types/IngressClass.ts
This change adds the Ingress Class resource viewer.
> feat: add ingress class resource viewer

- plugins/cad/src/components/AddPackagePage/AddPackagePage.tsx
- plugins/cad/src/components/LandingPage/LandingPage.tsx
- plugins/cad/src/components/PackageRevisionPage/components/PackageRevisionOptions.tsx
- plugins/cad/src/components/RegisterRepositoryPage/RegisterRepositoryPage.tsx
- plugins/cad/src/components/RepositoryListPage/RepositoryListPage.tsx
- plugins/cad/src/routes.ts
- plugins/cad/src/types/Repository.ts
- plugins/cad/src/utils/repository.ts
This change adds the concept of catalog blueprints which are blueprints which must be cloned to a blueprint repository and customized before being deployed to a deployment repository.
> feat: add catalog blueprints

- plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewers/StructuredMetadata/resources/service.ts
- plugins/cad/src/types/Service.ts
This change updates the service resource viewer.
> feat: update service resource viewer

- plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewerSelector.tsx
- plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewers/StructuredMetadata/resources/job.ts
- plugins/cad/src/types/Job.ts
This change adds the Job resource viewer.
> feat: add job resource viewer

- plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewerSelector.tsx
- plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewers/StructuredMetadata/resources/customResourceDefinition.ts
- plugins/cad/src/types/CustomResourceDefinition.ts
This change adds the Custom Resource Definition resource viewer.
> feat: add custom resource definition resource viewer

- plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewers/StructuredMetadata/resources/roleBinding.ts
- plugins/cad/src/types/RoleBinding.ts
This change updates the Role Binding and Cluster Role Binding resource viewers.
> feat: update role binding and cluster role binding resource viewers

- plugins/cad/src/components/ResourceEditorDialog/components/FirstClassEditors/RoleEditor/RoleEditor.tsx
- plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewers/StructuredMetadata/resources/role.ts
- plugins/cad/src/types/Role.ts
This change updates the Cluster Role and Role resource viewers.
> feat: update cluster role and role resource viewers

- plugins/cad/src/components/PackageRevisionPage/components/PackageResourcesList.tsx
- plugins/cad/src/components/PackageRevisionPage/components/PackageRevisionResourcesTable.tsx
- plugins/cad/src/utils/packageRevisionResources.ts
This change updates the Add Resource button on the Package Revision page to add the resource to the requested component.
> feat: add resource to requested component

- plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewerSelector.tsx
- plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewers/StructuredMetadata/resources/secret.ts
This change adds the Secret resource viewer.
> feat: add secret resource viewer

- plugins/cad/src/components/PackageRevisionPage/PackageRevisionPage.tsx
This change updates the Package Revision page to show an alert when downstream packages are not on the latest published revision of the current package.
> feat: alert when downstream packages can be upgraded

- plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewerSelector.tsx
- plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewers/StructuredMetadata/resources/apiService.ts
- plugins/cad/src/types/APIService.ts
This changes add the API Service resource viewer.
> feat: add api service resource viewer

- plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewerSelector.tsx
- plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewers/StructuredMetadata/resources/default.ts
This change adds the default resource viewer, which shows when a named resource viewer does not exist for a certain group version kind.
> feat: add default resource viewer

- plugins/cad/src/components/PackageRevisionPage/components/PackageRevisionResourcesTable.tsx
This change updates the Package Revision page to allow a Service resource to be added to a package.
> feat: allow service resources to be added

- plugins/cad/src/components/ResourceEditorDialog/components/FirstClassEditorSelector.tsx
- plugins/cad/src/components/ResourceEditorDialog/components/FirstClassEditors/IngressEditor/IngressEditor.tsx
- plugins/cad/src/components/ResourceEditorDialog/components/FirstClassEditors/IngressEditor/components/CustomControllerEditorAccordion.tsx
- plugins/cad/src/components/ResourceEditorDialog/components/FirstClassEditors/IngressEditor/components/DefaultBackendEditorAccordion.tsx
- plugins/cad/src/components/ResourceEditorDialog/components/FirstClassEditors/IngressEditor/components/HTTPPathRuleEditorAccordion.tsx
- plugins/cad/src/components/ResourceEditorDialog/components/FirstClassEditors/IngressEditor/components/IngressBackendPanel.tsx
- plugins/cad/src/components/ResourceEditorDialog/components/FirstClassEditors/IngressEditor/components/IngressRuleEditorAccordion.tsx
- plugins/cad/src/components/ResourceEditorDialog/components/FirstClassEditors/IngressEditor/components/TLSEditorAccordion.tsx
- plugins/cad/src/components/ResourceEditorDialog/components/FirstClassEditors/IngressEditor/index.ts
- plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewers/StructuredMetadata/resources/ingress.ts
- plugins/cad/src/types/Ingress.ts
This change adds the Ingress resource editor.
> feat: add ingress resource editor

- packages/app/package.json
- packages/app/src/App.tsx
- packages/app/src/components/Root/Root.tsx
- packages/app/src/components/catalog/EntityPage.tsx
- yarn.lock
This change removes api docs from the sample application.
> feat: remove api docs from sample application

- plugins/cad/src/components/PackageRevisionPage/components/PackageResourcesList.tsx
- plugins/cad/src/components/PackageRevisionPage/components/ResourcesTabContent.tsx
This change adds resource filtering options to the Package Revision page.
> feat: add resource filter options to package revision page

- plugins/cad/src/components/AddPackagePage/AddPackagePage.tsx
- plugins/cad/src/utils/repository.ts
This change improves the user flow of the Add Package page.
> feat: improve add package page user flow

- plugins/cad/src/components/RegisterRepositoryPage/RegisterRepositoryPage.tsx
- plugins/cad/src/utils/repository.ts
This change updates the repository content types renaming Blueprints to Team Blueprints, Catalog Blueprints to External Blueprints, and adding Organizational Blueprints.
> feat: update repository content types

- plugins/cad/src/components/ResourceEditorDialog/ResourceEditorDialog.tsx
This change increases the height and width of the Resource Editor Dialog.
> feat: update resource editor to use more screen space

- plugins/cad/src/components/ResourceViewerDialog/ResourceViewerDialog.tsx
This change increases the height and width of the Resource Viewer Dialog.
> feat: update resource viewer to use more screen space

- plugins/cad/src/components/ResourceEditorDialog/components/FirstClassEditorSelector.tsx
- plugins/cad/src/components/ResourceEditorDialog/components/FirstClassEditors/DeploymentEditor/StatefulSetEditor.tsx
- plugins/cad/src/components/ResourceEditorDialog/components/FirstClassEditors/DeploymentEditor/components/StatefulSetDetailsEditorAccordion.tsx
- plugins/cad/src/components/ResourceEditorDialog/components/FirstClassEditors/DeploymentEditor/components/statefulSet/UpdateStrategyEditorAccordion.tsx
- plugins/cad/src/components/ResourceEditorDialog/components/FirstClassEditors/DeploymentEditor/index.ts
- plugins/cad/src/types/StatefulSet.ts
This change adds the Stateful Set resource editor.
> feat: add stateful set resource editor

- plugins/cad/src/components/RepositoryPage/components/RepositoryDetails.tsx
- plugins/cad/src/types/Repository.ts
This change adds repository status conditions to the Repository Details Table.
> feat: add repository status conditions to repository details table

- plugins/cad/src/apis/ConfigAsDataApi.ts
- plugins/cad/src/apis/PorchRestApi.ts
- plugins/cad/src/components/PackageRevisionPage/PackageRevisionPage.tsx
- plugins/cad/src/types/PackageRevisionResource.ts
This change updates the Package Revision Page to show package rendering errors.
> feat: show render errors on package revision page

- plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewers/StructuredMetadata/resources/deployment.ts
- plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewers/StructuredMetadata/resources/podTemplate.ts
- plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewers/StructuredMetadata/resources/statefulSet.ts
This change updates the pod template metadata shown in the Deployment, Job, and Stateful Set resource viewers to show additional information.
> feat: update pod template resource viewer

- app-config.production.yaml
- app-config.yaml
- plugins/cad-backend/README.md
- plugins/cad-backend/src/service/config.ts
- plugins/cad-backend/src/service/router.ts
This change adds support for service account server side authentication.
> feat: add kubernetes service account authentication

- plugins/cad-backend/README.md
- plugins/cad-backend/src/service/config.ts
- plugins/cad-backend/src/service/router.ts
- plugins/cad/src/apis/PorchRestApi.ts
This change adds support for using Google OIDC authentication.
> feat: add support for google oidc authentication

- app-config.yaml
- plugins/cad-backend/README.md
- plugins/cad-backend/src/service/config.ts
- plugins/cad-backend/src/service/router.ts
- plugins/cad/src/apis/PorchRestApi.ts
This change updates the Porch resources namespace to be configuration based.
> feat: make porch resources namespace configurable

- plugins/cad/src/components/PackageRevisionPage/PackageRevisionPage.tsx
- plugins/cad/src/components/PackageRevisionPage/components/PackageRevisionsTable.tsx
This change adds a current revision visual indicator to the Package Revisions Table.
> feat: add current revision indicator to package revisions table

- plugins/cad/src/components/ResourceEditorDialog/components/FirstClassEditors/KptfileEditor/KptfileEditor.tsx
- plugins/cad/src/components/ResourceEditorDialog/components/FirstClassEditors/KptfileEditor/components/KptfileInfoEditorAccordion.tsx
This change updates the Kptfile Resource Editor to allow the package keywords and site to be updated.
> feat: update kptfile resource editor

- plugins/cad/src/components/PackageRevisionPage/PackageRevisionPage.tsx
- plugins/cad/src/components/PackageRevisionPage/components/ConditionsTable.tsx
- plugins/cad/src/types/PackageRevision.ts
- plugins/cad/src/utils/packageRevision.ts
This change updates the Package Revision Page to show package conditions.
> feat: show package conditions on package revision page

- packages/app/src/components/Root/Root.tsx
- plugins/cad/config.d.ts
- plugins/cad/src/components/LandingPage/LandingPage.tsx
This change updates the UI to allow branding.
> feat: allow branding

- plugins/cad/src/utils/packageRevision.ts
This change ensures that all draft and proposed package revisions are shown.
> feat: show all draft and proposed package revisions

- plugins/cad/src/components/PackageRevisionPage/components/ConditionsTable.tsx
This changes updates the styles of the Package Conditions Table.
> feat: update package conditions table styles

- plugins/cad/src/components/PackageManagementPage/PackageManagementPage.tsx
- plugins/cad/src/components/PackageManagementPage/components/ContentInfoCard.tsx
- plugins/cad/src/components/PackageManagementPage/components/DashboardTabContent.tsx
- plugins/cad/src/components/PackageManagementPage/components/RepositoriesTabContent.tsx
This change adds a dashboard to the Landing Page to surface quick information to the user.
> feat: add dashboard to landing page

- plugins/cad/src/components/PackageManagementPage/components/ContentInfoCard.tsx
- plugins/cad/src/utils/repository.ts
This change updates the dashboard to show if any of the repositories are in error.
> feat: update dashboard to show if repository is not ready

- plugins/cad/src/components/LandingPage/LandingPage.tsx
- plugins/cad/src/components/PackageManagementPage/components/ContentInfoCard.tsx
- plugins/cad/src/components/RepositoryPage/PackagesPage.tsx
- plugins/cad/src/components/RepositoryPage/RepositoryPage.tsx
- plugins/cad/src/components/RepositoryPage/components/PackagesTabContent.tsx
- plugins/cad/src/components/RepositoryPage/index.ts
- plugins/cad/src/routes.ts
- plugins/cad/src/utils/repository.ts
This change adds the Packages Page which allows the viewing of packages by content type.
> feat: allow viewing of all packages by content type

- plugins/cad/src/components/AddPackagePage/AddPackagePage.tsx
- plugins/cad/src/components/LandingPage/LandingPage.tsx
- plugins/cad/src/components/Links/PackagesLink.tsx
- plugins/cad/src/components/Links/index.ts
- plugins/cad/src/components/RepositoryPage/PackagesPage.tsx
- plugins/cad/src/components/RepositoryPage/RepositoryPage.tsx
- plugins/cad/src/routes.ts
- plugins/cad/src/utils/repository.ts
This changes adds the Add Package button to the Packages Page.
> feat: add add package button to packages page

- plugins/cad/src/components/PackageRevisionPage/components/PackageResourcesList.tsx
This change allows a resource's path to be updated with the `internal.config.kubernetes.io/path` annotation.
> feat: allow resource path to be updated

- plugins/cad/src/components/Links/PackageLink.tsx
- plugins/cad/src/components/PackageRevisionPage/PackageRevisionPage.tsx
- plugins/cad/src/utils/packageRevision.ts
This change updates the message shown on the Package Revision Page when an upgrade is available.
> feat: update package upgrade available message

- plugins/cad/src/utils/packageRevisionResources.ts
This change updates the filename generation logic for to assign unique filenames to new resources.
> feat: assign unique filenames to new resources

- plugins/cad/src/utils/packageRevision.ts
- plugins/cad/src/utils/repository.ts
Purely cosmetic, but makes the errors harder to understand!
> fix: Fix a few undefined variables in error messages

- package.json
- yarn.lock
This change updates dependencies to latest using `yarn upgrade`.
> build: bump dependencies

- packages/app/src/App.tsx
This change updates the Backstage app to use the latest recommended app setup.
> refactor: use new app setup

- app-config.yaml
This change removes unused configuration from the Backstage `app-config.yaml` file.
> chore: removed unused configuration from app config

- plugins/cad-backend/README.md
- plugins/cad-backend/src/service/config.ts
- plugins/cad-backend/src/service/router.ts
- plugins/cad/config.d.ts
This change allows the maximum HTTP request size to be configurable.
> feat: allow maximum http request size to be configurable

- plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewers/StructuredMetadata/resources/secret.ts
- plugins/cad/src/types/Secret.ts
This change updates the Secret Resource Viewer to display the secrets in the string data field and to base64 decode the secrets in the data field.
> feat: update secret resource viewer
