package.json

Fixes yarn lint in the example backstage application to use the main branch when determining the changes to lint.

build: fix yarn lint

---

.github/workflows/ci.yml
CONTRIBUTING.md

This change adds a new GitHub action to lint and test code for new pushes and pull requests.

ci: add github action to lint and test code

---

plugins/cad/src/components/Links/PackageLink.tsx
plugins/cad/src/components/PackageRevisionPage/PackageRevisionPage.tsx
plugins/cad/src/components/PackageRevisionPage/components/AdvancedPackageRevisionOptions.tsx
plugins/cad/src/utils/packageRevision.ts

This change updates the Package Revision Page header to show package name and revision as the title to clarify that single revision a the package is being viewed. The package descriptor is moved to the right of the header and shown with the lifecycle of the package which is now a standard div. The chip was removed to reduce confusion on whether it was a clickable element.

feat: update package revision page header

---

.github/header-checker-lint.yml

Add configuration for the [license header lint](https://github.com/googleapis/repo-automation-bots/tree/main/packages/header-checker-lint) to ensure all source files contain a valid license.

ci: add license header lint configuration

---

plugins/cad/src/components/PackageRevisionPage/PackageRevisionPage.tsx

Refactor css styles on the Package Revision Page so styles will automatically apply to new components. Look and feel remains the same to the user.

refactor: refactor css styles on package revision page

---

plugins/cad/src/components/PackageRevisionPage/PackageRevisionPage.tsx
plugins/cad/src/types/PackageRevision.ts
plugins/cad/src/utils/configSync.ts
plugins/cad/src/utils/packageRevision.ts

This change allows for new revisions of a package to be created. When a user is on the latest published revision of a package on the Package Revision Page, a 'Create New Revision' button will appear. Clicking on this button will copy the package into a new draft revision and update the page to show the new revision. When a new revision of a package is published, the sync (if one is already created for the package) will automatically update to the new published revision.

feat: create new revisions of a package

---

plugins/cad/src/components/Controls/PackageIcon.tsx
plugins/cad/src/components/Controls/index.ts
plugins/cad/src/components/RepositoryPage/components/PackageRevisionsTable.tsx

This change updates the Package Revisions Table by only allowing a package to consume a single row with the latest published revision of a package taking precedence. A status column is added to the table to display if any unpublished revisions of a package exists.

feat: update package revisions table

---

plugins/cad/src/components/PackageRevisionPage/PackageRevisionPage.tsx
plugins/cad/src/components/PackageRevisionPage/components/PackageRevisionsTable.tsx
plugins/cad/src/utils/formatDate.ts

This change adds a new revisions tab to the Package Revisions Page that lists all revisions of the selected package.

feat: list revisions of a package

---

package.json

This change adds a new script that formats all code to a consistent style. The can be executed by running `yarn prettier:write`.

chore: add script to format code

---

plugins/cad/src/components/PackageRevisionPage/PackageRevisionPage.tsx

This change renames the 'Move to Draft' button on the Package Revision Page to 'Reject' since a reviewer will either approve or reject the proposed package. The action of the button, moving the package back to the draft state, remains the same.

feat: rename move to draft button to reject

---

plugins/cad/src/components/PackageRevisionPage/components/PackageRevisionResourcesTable.tsx

This change updates the styles on the Delete button so the button no longer increase the row height of the Package Resources Table.

fix: resources table delete button no longer increases row height

---

plugins/cad/src/components/Controls/index.ts
plugins/cad/src/components/PackageRevisionPage/PackageRevisionPage.tsx

This change allows previously published revisions of a package to be restored. This is completed by clicking the new 'Restore Revision' button on the Package Revision Page when a previously published package revision is shown. Restore Revision will create a new revision of the package, resetting the resources to the revision is restore is requested for.

feat: add restore package revision

---

plugins/cad/src/apis/ConfigAsDataApi.ts
plugins/cad/src/apis/PorchRestApi.ts
plugins/cad/src/components/Links/PackageLink.tsx
plugins/cad/src/components/RepositoryPage/RepositoryPage.tsx
plugins/cad/src/components/RepositoryPage/components/PackageSummaryTable.tsx
plugins/cad/src/types/PackageRevisionResource.ts
plugins/cad/src/utils/packageRevisionResources.ts
plugins/cad/src/utils/packageSummary.ts

This change adds a column to the Package Summary Table that shows the name of the upstream package.

feat: show blueprint name on package summary table

---

plugins/cad/src/utils/yaml.ts

This change aligns the yaml formatting of the resource editors to the yaml formatting of Porch where an indentation level is not added array elements.

fix: do not add an indentation level to array elements

---

plugins/cad/src/components/RepositoryListPage/RepositoryListPage.tsx
plugins/cad/src/components/RepositoryListPage/components/RepositoriesTable.tsx
plugins/cad/src/types/RepositorySummary.ts
plugins/cad/src/utils/repositorySummary.ts

This change adds a column to the Repositories Table that shows the number of published, proposed, and draft packages in each repository.

feat: show package count on repositories table

---

plugins/cad/src/components/Controls/YamlViewer.tsx
plugins/cad/src/components/PackageRevisionPage/components/PackageRevisionResourcesTable.tsx
plugins/cad/src/components/ResourceViewerDialog/ResourceViewerDialog.tsx
plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewerSelector.tsx
plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewers/StructuredMetadata/StructuredMetadata.tsx

This change shows the exact changes, or diff, that an updated resource contains.

feat: show diff of individual package resources

---

plugins/cad/src/components/PackageRevisionPage/components/PackageRevisionResourcesTable.tsx

This change ensures only the resources that exist in the current package revision are passed to the Resource Editor Dialog.

fix: pass current package resources to resource editor dialog

---

plugins/cad/src/utils/yaml.ts

This change aligns the yaml formatting of the resource editors to kpt and Porch where double quotes are preferred over single quotes.

fix: use double quotes when serializing yaml

---

plugins/cad/src/components/PackageRevisionPage/PackageRevisionPage.tsx

This change ensures a task list is always specified when a new restore package revision is being created.

fix: specify tasks list when restoring a package revision

---

plugins/cad/src/components/PackageRevisionPage/PackageRevisionPage.tsx

This change updates the Compare Revision dropdown on the Package Revision Page to include all previous revisions. Previously the comparison dropdown only showed the last previous revision.

feat: show all previous revisions in compare revision dropdown

---

plugins/cad/src/components/PackageRevisionPage/PackageRevisionPage.tsx

This change updates the Compare Revision dropdown on the Package Revision Page to default to the most relevant revision when a new package revision is created. The dropdown will default to the previous revision when a new revision is created and to upstream when the very first revision of a package is created. The dropdown will default to none when viewing a published revision.

feat: default compare revision dropdown

---

plugins/cad/src/components/PackageRevisionPage/PackageRevisionPage.tsx
plugins/cad/src/components/RepositoryListPage/components/RepositoriesTable.tsx
plugins/cad/src/components/RepositoryPage/components/PackageSummaryTable.tsx
plugins/cad/src/utils/packageRevision.ts
plugins/cad/src/utils/packageSummary.ts

This change allows packages to be upgraded to use the latest published blueprint revision. A package can be upgraded by clicking the 'Upgrade to Latest Blueprint' button on the Package Revision Page. This button shows when the latest published revision of a package is shown, and there's a new published revision for the package's blueprint. Additionally, the Packages Table shows a visual indicator when upgrades are available for packages.

feat: add upgrade functionality

---

plugins/cad/src/apis/ConfigAsDataApi.ts
plugins/cad/src/apis/PorchRestApi.ts
plugins/cad/src/components/LandingPage/LandingPage.tsx
plugins/cad/src/components/PackageRevisionPage/PackageRevisionPage.tsx
plugins/cad/src/components/RepositoryPage/RepositoryPage.tsx
plugins/cad/src/types/ApiGroup.ts
plugins/cad/src/types/ConfigManagement.ts
plugins/cad/src/utils/featureFlags.ts

This change allows the Config as Data UI to use clusters that Config Sync is not installed on.

feat: config sync is optional

---

plugins/cad/src/components/PackageRevisionPage/PackageRevisionPage.tsx

This change ensures the Compare Revision dropdown on the Package Revision Page always lists the upstream package anytime the upstream package is known.

fix: allow upstream package comparison

---

plugins/cad/src/components/PackageRevisionPage/components/PackageRevisionOptions.tsx

This change ensures the 'Deploy' button shows on the Package Revision Page for the latest published revision of a blueprint.

fix: allow latest published blueprint to be deployed

---

plugins/cad/src/components/AddPackagePage/AddPackagePage.tsx
plugins/cad/src/components/PackageRevisionPage/components/PackageRevisionOptions.tsx
plugins/cad/src/utils/packageSummary.ts

This change allows blueprints to deployed to any deployment repository regardless if the deployment repository's upstream is set the blueprint's repository.

feat: allow blueprints to be deployed to any deployment repository

---

plugins/cad/src/components/PackageRevisionPage/components/PackageRevisionResourcesTable.tsx
plugins/cad/src/utils/packageRevisionResources.ts

This change adds a column to the Resources Table in the Package Revision Page to show the component that a resource belongs to.

feat: update resources table to show component a resource exists in

---

plugins/cad/src/components/RepositoryListPage/RepositoryListPage.tsx
plugins/cad/src/components/RepositoryListPage/components/RepositoriesTable.tsx
plugins/cad/src/utils/repository.ts

This change updates the Landing Page to list all package repositories in the same tab instead of creating separate tabs for each package repository content type (deployments, blueprints, catalog blueprints).

feat: update repositories list on landing page

---

plugins/cad/src/components/ResourceViewerDialog/ResourceViewerDialog.tsx

This change ensures that white space is always preserved in the resource viewers. Preserving of white space allows resources with multiline values to be correctly displayed.

feat: preserve white space in resource viewers

---

plugins/cad/src/components/PackageRevisionPage/PackageRevisionPage.tsx
plugins/cad/src/components/RepositoryPage/RepositoryPage.tsx
plugins/cad/src/utils/packageRevision.ts
plugins/cad/src/utils/packageSummary.ts
plugins/cad/src/utils/repository.ts
plugins/cad/src/utils/repositorySummary.ts

This change allows packages to have the same name across different repositories.

feat: allow packages with the same name across different repositories

---

plugins/cad/src/utils/packageRevisionResources.ts

This change updates the resource diff logic to ignore whitespace when comparing yaml.

feat: ignore whitespace in resource yaml diff

---

plugins/cad/src/components/PackageRevisionPage/components/PackageResourcesList.tsx
plugins/cad/src/components/PackageRevisionPage/components/PackageRevisionResourcesTable.tsx
plugins/cad/src/utils/packageRevisionResources.ts

This change creates a separate Resources Table for each component in the package's resources on the Package Revisions Page, removing the component column previously added to the Resources Table.

feat: create separate resources table for each component

---

plugins/cad/src/components/PackageRevisionPage/PackageRevisionPage.tsx
plugins/cad/src/components/PackageRevisionPage/components/DownstreamTabContent.tsx
plugins/cad/src/components/PackagesTable/PackagesTable.tsx
plugins/cad/src/utils/packageSummary.ts
plugins/cad/src/utils/repository.ts

This change adds the Downstream tab to the Package Revision page to show the downstream packages for the current package. The tab is hidden for deployment packages since deployments will not have any downstream packages.

feat: show downstream packages

---

plugins/cad/src/components/PackageRevisionPage/PackageRevisionPage.tsx
plugins/cad/src/components/PackageRevisionPage/components/RelatedPackagesContent.tsx

This change updates the Package Revision page to include a link to the upstream blueprint and downstream package summary.

feat: add related package summary on package revision page

---

plugins/cad/src/components/PackageRevisionPage/components/PackageRevisionResourcesTable.tsx

This change allows the resource editors access the resource list of the package.

fix: allow resource editors access to current resources list

---

plugins/cad/src/components/ResourceEditorDialog/components/FirstClassEditors/ApplyReplacementsEditor/ApplyReplacementsEditor.tsx
plugins/cad/src/components/ResourceEditorDialog/components/FirstClassEditors/ConfigMapEditor/ConfigMapEditor.tsx
plugins/cad/src/components/ResourceEditorDialog/components/FirstClassEditors/Controls/ResourceMetadataAccordion.tsx
plugins/cad/src/components/ResourceEditorDialog/components/FirstClassEditors/KptfileEditor/KptfileEditor.tsx
plugins/cad/src/components/ResourceEditorDialog/components/FirstClassEditors/NamespaceEditor/NamespaceEditor.tsx
plugins/cad/src/components/ResourceEditorDialog/components/FirstClassEditors/ResourceQuotaEditor/ResourceQuotaEditor.tsx
plugins/cad/src/components/ResourceEditorDialog/components/FirstClassEditors/RoleBindingEditor/RoleBindingEditor.tsx
plugins/cad/src/components/ResourceEditorDialog/components/FirstClassEditors/RoleEditor/RoleEditor.tsx
plugins/cad/src/components/ResourceEditorDialog/components/FirstClassEditors/ServiceAccountEditor/ServiceAccountEditor.tsx
plugins/cad/src/components/ResourceEditorDialog/components/FirstClassEditors/ServiceEditor/ServiceEditor.tsx
plugins/cad/src/components/ResourceEditorDialog/components/FirstClassEditors/SetLabelsEditor/SetLabelsEditor.tsx

This change updates the resource editors so the resource's name, namespace, labels, and annotations now appear within the Resources Metadata group.

feat: group resource metadata in resource editors

---

plugins/cad/src/components/PackageRevisionPage/components/PackageRevisionResourcesTable.tsx

This change updates the Package Revision page to allow an Ingress resource to be added to a package.

feat: allow ingress resource to be added

---

packages/app/src/App.tsx

This change updates the sample Backstage application to redirect to the Config as Data plugin when the base url is entered.

feat: redirect base url to config as data plugin

---

plugins/cad/src/components/RepositoryPage/components/AdvancedRepositoryOptions.tsx
plugins/cad/src/components/RepositoryPage/components/RepositoryDetails.tsx

This change adds details of the current repository to the Advanced tab of the Repository Page.

feat: add repository details to repository page

---

plugins/cad/src/components/PackageRevisionPage/components/PackageRevisionResourcesTable.tsx
plugins/cad/src/utils/packageRevisionResources.ts

This change adds a visual indicator to local config resources in the Resources table.

feat: add local config indicator to resources table

---

plugins/cad/src/components/PackageRevisionPage/components/PackageRevisionResourcesTable.tsx

This change updates the Add Resource button on the Package Revision page to default the namespace of the new resource to the namespace other resources within the package are using if a namespace resource does not exist.

feat: update add resource default namespace logic

---

plugins/cad/src/components/AddPackagePage/AddPackagePage.tsx
plugins/cad/src/components/LandingPage/LandingPage.tsx
plugins/cad/src/components/PackageRevisionPage/components/PackageRevisionOptions.tsx
plugins/cad/src/routes.ts
plugins/cad/src/utils/packageRevision.ts

This change updates the Package Revision consolidating the Deploy button into the Clone button.

feat: consolidate clone and deploy buttons on package revision page

---

plugins/cad/src/components/PackageRevisionPage/components/PackageRevisionResourcesTable.tsx

This change ensures that a unique column will always be used for diff on the Resources Table.

fix: use unique resources table column for diff

---

plugins/cad/src/components/ResourceEditorDialog/ResourceEditorDialog.tsx
plugins/cad/src/components/ResourceEditorDialog/components/FirstClassEditorSelector.tsx

This change updates the Resource Editor Dialog to show the yaml editor on open when a named resource editor does not exist.

feat: update resource editor to show yaml when no named editor exists

---

plugins/cad/src/utils/packageRevision.ts
plugins/cad/src/utils/repository.ts

This change updates the upstream package revision logic increasing flexibility with the git repository match and only returning upstream information if the package name and revision delimiter is found within the upstream lock git reference.

feat: update upstream package logic

---

plugins/cad/src/components/Controls/RadioGroup.tsx
plugins/cad/src/components/Controls/index.ts
plugins/cad/src/components/RegisterRepositoryPage/RegisterRepositoryPage.tsx
plugins/cad/src/utils/repository.ts

This change updates the Register Repository Page adding descriptions to the repository content types.

feat: add content type descriptions to register repository page

---

plugins/cad/src/components/ResourceEditorDialog/ResourceEditorDialog.tsx

This change updates the title of the Resource Editor Dialog to 'New Resource' when the dialog is opened for a new resource.

fix: update resource editor title when showing a new resource

---

plugins/cad/src/components/PackageRevisionPage/components/PackageResourcesList.tsx

This change updates the Resources Table to show resources with the config.kubernetes.io/local-config annotation first.

feat: update resources table to show local config resources first

---

plugins/cad/src/utils/packageSummary.ts

This change updates the package upgrade available logic to ensure packages are not incorrectly flagged as upgrade available.

fix: update package upgrade available logic

---

plugins/cad/src/components/AddPackagePage/AddPackagePage.tsx
plugins/cad/src/types/Kptfile.ts
plugins/cad/src/utils/packageRevisionResources.ts
plugins/cad/src/utils/string.ts

This change updates the Add Package Page to allow the Kptfile description, keywords, and site to be updated when a package is being cloned.

feat: allow kptfile information to be updated when cloning a package

---

plugins/cad/src/components/AddPackagePage/AddPackagePage.tsx
plugins/cad/src/components/Controls/Checkbox.tsx
plugins/cad/src/components/Controls/index.ts
plugins/cad/src/utils/function.ts
plugins/cad/src/utils/packageRevisionResources.ts

This change adds a Validate Resources step to the Add Package Page. This step allows users to have their package resources validated against their schema by adding the kubeval validator function to the Kptfile.

feat: add validate resources step on add package page

---

plugins/cad/src/components/AddPackagePage/AddPackagePage.tsx
plugins/cad/src/utils/repository.ts

This change updates the Add Package Page to show a warning when a deployment package is being created from an organizational or external blueprint. Ideally, a deployment package should be created from a team blueprint.

feat: show warning when creating a deployment not from a team blueprint

---

plugins/cad/src/components/AddPackagePage/AddPackagePage.tsx
plugins/cad/src/components/AddPackagePage/utils/namespaceState.ts
plugins/cad/src/types/SetNamespace.ts

This change updates the Add Package Page to allow the namespace to be customized when a package is being created from scratch or cloned from another package.

feat: allow namespace customization on add package page

---

plugins/cad/src/components/RegisterRepositoryPage/RegisterRepositoryPage.tsx
plugins/cad/src/components/RepositoryPage/components/RepositoryDetails.tsx
plugins/cad/src/utils/repository.ts

This change updates the Register Repository Page to request the deployment environment (development, staging, or production) when the repository content type is deployments.

feat: add deployment environment to register repository page

---

plugins/cad/src/utils/repository.ts
plugins/cad/src/utils/string.ts

This change allows a package's upstream repository to be found if the package's upstream lock was based off an upstream that was fetched using ssh while the upstream repository in Porch was registered with https.

feat: add git ssh url support for finding upstream repository

---

plugins/cad/src/components/ResourceEditorDialog/components/FirstClassEditors/KptfileEditor/components/KptFunctionEditorAccordion.tsx

This change updates the function selection logic in the Kptfile resource editor to avoid selecting a catalog function when a custom function has a similar name and tag however exists in a different repository.

fix: update kptfile editor function selection logic

---

plugins/cad/src/utils/kubernetesResource.ts
plugins/cad/src/utils/packageRevisionResources.ts

This change updates the Package Revision Page to normalize resources prior to the package revisions's resources being compared with another revision. Normalizing resources includes removing any internal kpt annotations, any comments, and standardizing the yaml indentation.

feat: update package revision page to normalize resources prior to diff

---

plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewers/StructuredMetadata/StructuredMetadata.tsx

This changes updates the base metadata shown for a resource on the Resource Viewer Dialog. This includes filtering out any internal kpt annotations and combining the resource's kind and name into a single entry.

feat: update base metadata shown on resource viewer

---

plugins/cad/src/components/PackageRevisionPage/components/PackageRevisionResourcesTable.tsx

This change updates the Package Revision page to allow a Deployment resource to be added to a package.

feat: allow deployment resource to be added

---

plugins/cad/src/components/PackageRevisionPage/components/PackageRevisionResourcesTable.tsx

This change updates the Package Revision page to allow a Stateful Set resource to be added to a package.

feat: allow stateful set resource to be added

---

plugins/cad/src/components/PackageRevisionPage/components/PackageRevisionsTable.tsx
plugins/cad/src/components/PackagesTable/PackagesTable.tsx
plugins/cad/src/types/PackageRevision.ts
plugins/cad/src/utils/packageRevision.ts

This change allows the UI to work with the latest version of Porch where workspace name is required to create new package revisions and revision numbers are not assigned until a package revision is published .

feat: use porch workspace name

---

plugins/cad-backend/README.md
plugins/cad-backend/src/service/config.ts
plugins/cad-backend/src/service/router.ts
plugins/cad/src/apis/PorchRestApi.ts
plugins/cad/src/plugin.ts

This change adds support for using Okta authentication.

feat: add support for okta authentication

---

plugins/cad/src/components/AddPackagePage/AddPackagePage.tsx
plugins/cad/src/components/PackageRevisionPage/PackageRevisionPage.tsx
plugins/cad/src/components/PackageRevisionPage/components/AdvancedPackageRevisionOptions.tsx
plugins/cad/src/components/PackageRevisionPage/components/PackageRevisionOptions.tsx
plugins/cad/src/components/RegisterRepositoryPage/RegisterRepositoryPage.tsx
plugins/cad/src/components/RepositoryPage/RepositoryPage.tsx
plugins/cad/src/components/RepositoryPage/components/PackagesTabContent.tsx
plugins/cad/src/components/RepositoryPage/components/RepositoryDetails.tsx
plugins/cad/src/utils/repository.ts

This change updates the Register Repository Page to request if the repository has read-only access when a repository is being registered. If a repository is read-only, the UI will hide any options to add or update packages in the repository.

feat: add support for readonly repositories

---

plugins/cad/src/components/AddPackagePage/AddPackagePage.tsx

This change updates the Add Package Page to allow users to recover from errors that may occur when adding a package.

feat: allow error recovery on add package page

---

app-config.yaml
plugins/cad-backend/README.md
plugins/cad-backend/src/service/config.ts
plugins/cad-backend/src/service/router.ts
plugins/cad/src/apis/ConfigAsDataApi.ts
plugins/cad/src/apis/PorchRestApi.ts
plugins/cad/src/types/Features.ts
plugins/cad/src/utils/featureFlags.ts

This change updates the GitOps delivery tool to be configurable instead of always defaulting to Config Sync.

feat: allow git ops tool to be configurable

---

plugins/cad/src/components/Controls/Chip.tsx
plugins/cad/src/components/Controls/index.ts
plugins/cad/src/components/PackageManagementPage/components/ContentInfoCard.tsx
plugins/cad/src/components/RepositoryPage/components/PackagesTabContent.tsx
plugins/cad/src/utils/packageSummary.ts

This change updates the Packages Page and Repository Page to allow filters to be applied to the Packages Table so only draft, proposed, published, and upgrade available packages are shown.

feat: allow filtering of packages

---

plugins/cad/src/components/PackagesTable/PackagesTable.tsx

This change updates the repository column on the Packages Table to show the repository name without the link.

feat: remove repository link from packages table

---

plugins/cad/src/components/PackagesTable/PackagesTable.tsx

This change removes the lifecycle column from the Packages Table.

feat: remove lifecycle column from packages table

---

plugins/cad/src/components/PackageRevisionPage/PackageRevisionPage.tsx
plugins/cad/src/utils/configSync.ts

This change ensures a sync (if one is already created for the package) is automatically updated to use the latest published revision of a package when a new revision is published through the UI.

fix: automatically update sync when new revision is published

---

plugins/cad/src/components/Links/RegisterRepositoryLink.tsx
plugins/cad/src/components/PackageManagementPage/components/ContentInfoCard.tsx

This change updates the Content Info Card to show a register repository link when there are no repositories registered for the content type.

feat: show register repository link on landing page content cards

---

plugins/cad/src/components/RegisterRepositoryPage/RegisterRepositoryPage.tsx
plugins/cad/src/components/RepositoryPage/components/RepositoryDetails.tsx
plugins/cad/src/utils/repository.ts

This change updates the Register Repository Page removing the deployment environment selection when the repository content type is set to deployments.

feat: remove deployment environment from register repository page

---

plugins/cad/src/components/PackageManagementPage/components/RepositoriesTabContent.tsx
plugins/cad/src/components/PackageRevisionPage/components/PackageRevisionOptions.tsx
plugins/cad/src/components/RepositoryPage/PackagesPage.tsx
plugins/cad/src/components/RepositoryPage/RepositoryPage.tsx

This change updates the UI to use the link button as the backstage button core component is now deprecated.

refactor: replace backstage button with link button

---

hack/install-porch.sh

This change updates the `./install-porch.sh` script to avoid using the --one-top-level option with tar since this option isn't available in all distributions of tar.

chore: update install porch script to avoid top level tar option

---

packages/app/package.json
packages/app/src/App.tsx
packages/backend/package.json
packages/backend/src/index.ts
packages/backend/src/plugins/catalog.ts
yarn.lock

This change allows the Settings page to show successfully by importing the Software Catalog. The Settings page was recently updated in Backstage to enable linking to the Software Catalog, thus requiring the plugin to be imported.

fix: allow settings page to show without error

---

plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewers/StructuredMetadata/StructuredMetadata.tsx
plugins/cad/src/components/ResourceViewerDialog/components/FirstClassViewers/StructuredMetadata/resources/default.ts

This change fixes an issue where the Resource Viewer Dialog crashes when the object to be displayed contains a field set to null.

fix: update resource viewer to handle null fields

---

plugins/cad/src/components/AddPackagePage/AddPackagePage.tsx
plugins/cad/src/components/PackageRevisionPage/PackageRevisionPage.tsx
plugins/cad/src/types/PackageRevisionResource.ts
plugins/cad/src/utils/packageRevisionResources.ts

This change updates the UI to support Porch optimistic concurrency control for package updates.

feat: add support for porch resource version checks
